name: Build Spek Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up MSYS2 for MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
        msystem: MINGW64

    - name: Add MSYS2 to PATH
      run: echo "::add-path::C:/msys64/mingw64/bin"

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
        cmake --build .

    - name: Upload the Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: spek.exe
        path: build/spek.exe
