name: Minimal Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: List directory contents
      shell: pwsh
      run: |
        Write-Output "Root directory contents:"
        Get-ChildItem -Force
        Write-Output "Full directory structure:"
        Get-ChildItem -Force -Recurse | Select-Object FullName

    - name: Setup MinGW
      shell: pwsh
      run: |
        choco install mingw
        $env:PATH += ";C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "Machine")
        Write-Output "Updated PATH: $env:PATH"

    - name: Verify GCC installation
      run: gcc --version

    - name: Compile project
      shell: pwsh
      run: |
        $cppFiles = Get-ChildItem -Recurse -Filter *.cpp
        if ($cppFiles.Count -gt 0) {
          Write-Output "Found the following .cpp files:"
          $cppFiles | ForEach-Object { Write-Output $_.FullName }
          $cppFilesList = $cppFiles.FullName -join ' '
          $command = "g++ -o spek.exe $cppFilesList"
          Write-Output "Executing command: $command"
          Invoke-Expression $command
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Compilation failed"
            exit 1
          }
        } else {
          Write-Output "No .cpp files found. Please check your project structure."
          exit 1
        }

    - name: Verify compilation result
      shell: pwsh
      run: |
        if (Test-Path spek.exe) {
          Write-Output "spek.exe was successfully created"
          Get-Item spek.exe | Select-Object FullName, Length, CreationTime, LastWriteTime
        } else {
          Write-Output "spek.exe was not created. Current directory contents:"
          Get-ChildItem
          exit 1
        }

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: spek
        path: spek.exe
